// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: patch/go.proto

package patch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Options represent Go-specific options for Protobuf messages, fields, oneofs, enums, or enum values.
type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name option renames the generated Go identifier and related identifiers.
	// For a message, this renames the generated Go struct and nested messages or enums, if any.
	// For a message field, this renames the generated Go struct field and getter method.
	// For a oneof field, this renames the generated Go struct field, getter method, interface type, and wrapper types.
	// For an enum, this renames the generated Go type.
	// For an enum value, this renames the generated Go const.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The type option changes the generated field type.
	// All generated code assumes that this type is castable to the protocol buffer field type.
	Type *string `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// The tags option specifies additional struct tags which are appended a generated Go struct field.
	// This option may be specified on a message field or a oneof field.
	// The value should omit the enclosing backticks.
	Tags *string `protobuf:"bytes,20,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	// The nullable option specifies whether the field is object value or pointer.
	// If true, the field is object value.
	// If false, the field is pointer.
	// If not specified, the field is pointer.
	Nullable      *bool `protobuf:"varint,30,opt,name=nullable,proto3,oneof" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_patch_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_patch_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_patch_go_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Options) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Options) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

func (x *Options) GetNullable() bool {
	if x != nil && x.Nullable != nil {
		return *x.Nullable
	}
	return false
}

var file_patch_go_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Options)(nil),
		Field:         7001,
		Name:          "go.field",
		Tag:           "bytes,7001,opt,name=field",
		Filename:      "patch/go.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional go.Options field = 7001;
	E_Field = &file_patch_go_proto_extTypes[0]
)

var File_patch_go_proto protoreflect.FileDescriptor

const file_patch_go_proto_rawDesc = "" +
	"\n" +
	"\x0epatch/go.proto\x12\x02go\x1a google/protobuf/descriptor.proto\"\x9d\x01\n" +
	"\aOptions\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04tags\x18\x14 \x01(\tH\x02R\x04tags\x88\x01\x01\x12\x1f\n" +
	"\bnullable\x18\x1e \x01(\bH\x03R\bnullable\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\a\n" +
	"\x05_tagsB\v\n" +
	"\t_nullable:D\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xd96 \x01(\v2\v.go.OptionsR\x05field\x88\x01\x01B\x1aZ\x18go-gen-patch/patch/patchb\x06proto3"

var (
	file_patch_go_proto_rawDescOnce sync.Once
	file_patch_go_proto_rawDescData []byte
)

func file_patch_go_proto_rawDescGZIP() []byte {
	file_patch_go_proto_rawDescOnce.Do(func() {
		file_patch_go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patch_go_proto_rawDesc), len(file_patch_go_proto_rawDesc)))
	})
	return file_patch_go_proto_rawDescData
}

var file_patch_go_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_patch_go_proto_goTypes = []any{
	(*Options)(nil),                   // 0: go.Options
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_patch_go_proto_depIdxs = []int32{
	1, // 0: go.field:extendee -> google.protobuf.FieldOptions
	0, // 1: go.field:type_name -> go.Options
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_patch_go_proto_init() }
func file_patch_go_proto_init() {
	if File_patch_go_proto != nil {
		return
	}
	file_patch_go_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patch_go_proto_rawDesc), len(file_patch_go_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_patch_go_proto_goTypes,
		DependencyIndexes: file_patch_go_proto_depIdxs,
		MessageInfos:      file_patch_go_proto_msgTypes,
		ExtensionInfos:    file_patch_go_proto_extTypes,
	}.Build()
	File_patch_go_proto = out.File
	file_patch_go_proto_goTypes = nil
	file_patch_go_proto_depIdxs = nil
}
