// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tests/nullable_test.proto

package tests

import (
	_ "go-gen-patch/patch"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullableType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullableType) Reset() {
	*x = NullableType{}
	mi := &file_tests_nullable_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullableType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableType) ProtoMessage() {}

func (x *NullableType) ProtoReflect() protoreflect.Message {
	mi := &file_tests_nullable_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableType.ProtoReflect.Descriptor instead.
func (*NullableType) Descriptor() ([]byte, []int) {
	return file_tests_nullable_test_proto_rawDescGZIP(), []int{0}
}

func (x *NullableType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Test struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// string id = 1;
	NullableName  NullableType `protobuf:"bytes,2,opt,name=nullable_name,json=nullableName,proto3" json:"nullable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_tests_nullable_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_tests_nullable_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_tests_nullable_test_proto_rawDescGZIP(), []int{1}
}

func (x *Test) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Test) GetNullableName() NullableType {
	if x != nil {
		return x.NullableName
	}
	return NullableType{}
}

var File_tests_nullable_test_proto protoreflect.FileDescriptor

const file_tests_nullable_test_proto_rawDesc = "" +
	"\n" +
	"\x19tests/nullable_test.proto\x12\x05tests\x1a\x0epatch/go.proto\"\"\n" +
	"\fNullableType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"c\n" +
	"\x04Test\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\bʵ\x03\x04\n" +
	"\x02IDR\x02id\x12A\n" +
	"\rnullable_name\x18\x02 \x01(\v2\x13.tests.NullableTypeB\aʵ\x03\x03\xf0\x01\x01R\fnullableName22\n" +
	"\vTestService\x12#\n" +
	"\aGetTest\x12\v.tests.Test\x1a\v.tests.TestB\x14Z\x12go-gen-patch/testsb\x06proto3"

var (
	file_tests_nullable_test_proto_rawDescOnce sync.Once
	file_tests_nullable_test_proto_rawDescData []byte
)

func file_tests_nullable_test_proto_rawDescGZIP() []byte {
	file_tests_nullable_test_proto_rawDescOnce.Do(func() {
		file_tests_nullable_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_nullable_test_proto_rawDesc), len(file_tests_nullable_test_proto_rawDesc)))
	})
	return file_tests_nullable_test_proto_rawDescData
}

var file_tests_nullable_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_nullable_test_proto_goTypes = []any{
	(*NullableType)(nil), // 0: tests.NullableType
	(*Test)(nil),         // 1: tests.Test
}
var file_tests_nullable_test_proto_depIdxs = []int32{
	0, // 0: tests.Test.nullable_name:type_name -> tests.NullableType
	1, // 1: tests.TestService.GetTest:input_type -> tests.Test
	1, // 2: tests.TestService.GetTest:output_type -> tests.Test
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_nullable_test_proto_init() }
func file_tests_nullable_test_proto_init() {
	if File_tests_nullable_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_nullable_test_proto_rawDesc), len(file_tests_nullable_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tests_nullable_test_proto_goTypes,
		DependencyIndexes: file_tests_nullable_test_proto_depIdxs,
		MessageInfos:      file_tests_nullable_test_proto_msgTypes,
	}.Build()
	File_tests_nullable_test_proto = out.File
	file_tests_nullable_test_proto_goTypes = nil
	file_tests_nullable_test_proto_depIdxs = nil
}
